changed format to fstring literal
GrafeasGroup/tor_archivist pull request #5
Opened 2017-12-01 13:35 UTC by yukilikespie

2017-12-01 13:52 UTC, perryprog requested changes
Seems like some other lines are also too long, but it's not your fault. #blamejoker

Blah blah see other main review in main tor repo

2017-12-01 13:52 UTC, perryprog commented on tor_archivist/main.py
> +                f'Post "{post.title}" is older than maximum age of {hours} hours, removing.'
This line is too long

2017-12-01 20:17 UTC, perryprog approved these changes

2017-12-02 16:23 UTC, TheLonelyGhost approved these changes
Great work! We really appreciate it! 👍

2017-12-02 16:23 UTC, merged